"""Framework-independent contracts and evaluation services for ML Studio."""

from .contracts import (
    CONTRACT_VERSION,
    CandidateSelectionEvidence,
    ColumnProfile,
    DatasetSnapshotIdentity,
    EvaluationResult,
    ExperimentSpecification,
    FeatureInfluence,
    FeatureRoles,
    FinalHoldoutEvidence,
    FoldEvidence,
    LeakageFinding,
    MetricPolicy,
    RandomSeedPolicy,
    ResourceLimits,
    ReviewedCandidateReference,
    RunSpecification,
    SelectionEvidence,
    SourceFingerprint,
    SplitPolicy,
    SplitEvidence,
    StructuredError,
    TruthBoundary,
)

__all__ = [
    "CONTRACT_VERSION",
    "CandidateSelectionEvidence",
    "ColumnProfile",
    "DatasetSnapshotIdentity",
    "EvaluationResult",
    "ExperimentSpecification",
    "FeatureInfluence",
    "FeatureRoles",
    "FinalHoldoutEvidence",
    "FoldEvidence",
    "LeakageFinding",
    "MetricPolicy",
    "RandomSeedPolicy",
    "ResourceLimits",
    "ReviewedCandidateReference",
    "RunSpecification",
    "SelectionEvidence",
    "SourceFingerprint",
    "SplitPolicy",
    "SplitEvidence",
    "StructuredError",
    "TruthBoundary",
]
