"""Framework-independent contracts, evaluation, and durability for ML Studio."""

from .artifacts import ArtifactMetadata, ArtifactStoreError, ManagedArtifactStore

from .contracts import (
    CONTRACT_VERSION,
    CandidateSelectionEvidence,
    ColumnProfile,
    DatasetSnapshotIdentity,
    EvaluationResult,
    ExperimentSpecification,
    FeatureInfluence,
    FeatureRoles,
    FinalHoldoutEvidence,
    FoldEvidence,
    LeakageFinding,
    MetricPolicy,
    PreparationAssessment,
    PreparationIssue,
    RandomSeedPolicy,
    ResourceLimits,
    ReviewedCandidateReference,
    RunSpecification,
    SelectionEvidence,
    SourceFingerprint,
    SplitPolicy,
    SplitEvidence,
    StructuredError,
    SuggestedPreparationFix,
    TransformationRecipeLineage,
    TransformationStep,
    TruthBoundary,
)
from .repository import MLStudioRepository, PersistenceError
from .service import MLStudioService, MLStudioServiceError

__all__ = [
    "ArtifactMetadata",
    "ArtifactStoreError",
    "CONTRACT_VERSION",
    "CandidateSelectionEvidence",
    "ColumnProfile",
    "DatasetSnapshotIdentity",
    "EvaluationResult",
    "ExperimentSpecification",
    "FeatureInfluence",
    "FeatureRoles",
    "FinalHoldoutEvidence",
    "FoldEvidence",
    "LeakageFinding",
    "MetricPolicy",
    "PreparationAssessment",
    "PreparationIssue",
    "MLStudioRepository",
    "MLStudioService",
    "MLStudioServiceError",
    "ManagedArtifactStore",
    "PersistenceError",
    "RandomSeedPolicy",
    "ResourceLimits",
    "ReviewedCandidateReference",
    "RunSpecification",
    "SelectionEvidence",
    "SourceFingerprint",
    "SplitPolicy",
    "SplitEvidence",
    "StructuredError",
    "SuggestedPreparationFix",
    "TransformationRecipeLineage",
    "TransformationStep",
    "TruthBoundary",
]
